# Generated by Django 5.0.4 on 2024-06-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCasa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva_restaurante',
            name='nota',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reserva_restaurante',
            name='num_personas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reserva_restaurante',
            name='turno',
            field=models.CharField(default='tarde', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='max_personas_reserva',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='max_reservas_dia',
            field=models.IntegerField(default=5),
        ),
    ]
