# Generated by Django 5.0.4 on 2024-06-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCasa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='img_url',
            field=models.CharField(default='appCasa/images/house.avif', max_length=255),
        ),
    ]
