# Generated by Django 5.0.4 on 2024-06-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCasa', '0002_reserva_restaurante_nota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='reserva',
        ),
        migrations.AlterField(
            model_name='reserva_restaurante',
            name='num_comensales',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='Evaluacion',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
