# Generated by Django 5.0.4 on 2024-06-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCasa', '0002_casa_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='img_url',
            field=models.CharField(default='house.avif', max_length=255),
        ),
    ]
