# Generated by Django 5.0.4 on 2024-06-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCasa', '0003_alter_casa_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='url_name',
            field=models.CharField(default='casas_panel', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='img_url',
            field=models.CharField(default='house.avif', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='url_name',
            field=models.CharField(default='index', max_length=255),
        ),
    ]
